### ISSUE TITLE
What is the command of scrna-subsets-master?

### ISSUE THREAD

**Issue by yueli8** [rnabioco/scrna-subsets#5]
Hello kriemo,

Thank you for developing so nice software: `scrna-subsets`.

I have already installed the software. What is the command?

Thank you in advance for your great help!

Best,

Yue

```
(.venv) li@li-HP-Pavilion-Desktop-590-p0xxx:~/scrna-subsets-master/bin$ ./scrna-subset -h
bash: ./scrna-subset: No such file or directory

```

**Comment by kriemo** [comment]
Hi Yue,
  Thanks for your interest. Can you briefly explain what you are trying to accomplish? This repo contains scripts and a pipeline to reproduce the analysis in a publication, but is not a standalone software tool.

**Comment by yueli8** [comment]
Hello, kriemo，

Thank you so much for your response!

I already downloaded the package of `scrna-subsets-master`,  `./configure,` `make` and `make install`.

How can I know I have already installed successfully and the manual of that software?

Normally,   the command `-h` will come out to confirm the installation and the manual.

What is the command of scrna-subset `-h` command?

Thank you in advance for your great help!


Best,


Yue

**Comment by kriemo** [comment]
Hi Yue, 
  I am confused, can you explain what analysis or data processing you are trying to perform with this code?  There is no `./configure` script and there is not code to generate a `./scrna-subsets` command in this repo. You can build some simple c++ utility functions in `bin` using `make`, but this is a repo for documenting code used in a publication, and is not a standalone software tool.

**Comment by yueli8** [comment]
Hello, kriemo,

Thank you for your message!

If I go to `bin,` and `make`, it will come out error.

Thank you again!

Best,

Yue

```

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin$ make
g++ -ggdb -Wall -O2 -std=c++0x  -Ihtslib -o barcode_tag_bam barcode_tag_bam.cpp bamreader.cpp molecules.cpp -lz -lm -lpthread htslib/libhts.a
barcode_tag_bam.cpp: In function ‘int main(int, char**)’:
barcode_tag_bam.cpp:76:16: warning: ignoring return value of ‘int sam_hdr_write(samFile*, const bam_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   sam_hdr_write(fp_out, header) ;
   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
barcode_tag_bam.cpp:115:15: warning: ignoring return value of ‘int sam_write1(samFile*, const bam_hdr_t*, const bam1_t*)’, declared with attribute warn_unused_result [-Wunused-result]
     sam_write1(fp_out, header, aln) ; //write alignment
     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
htslib/libhts.a(bgzf.o): In function `bgzf_write_init':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:209: undefined reference to `deflateInit2_'
htslib/libhts.a(bgzf.o): In function `inflate_gzip_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:451: undefined reference to `inflate'
htslib/libhts.a(bgzf.o): In function `bgzf_open':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:237: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_dopen':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:260: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_hopen':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:283: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_compress':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:311: undefined reference to `deflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:319: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:326: undefined reference to `deflateEnd'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:338: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:338: undefined reference to `crc32'
htslib/libhts.a(bgzf.o): In function `bgzf_gzip_compress':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:353: undefined reference to `deflate'
htslib/libhts.a(bgzf.o): In function `inflate_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:399: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:408: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:422: undefined reference to `inflateEnd'
htslib/libhts.a(bgzf.o): In function `bgzf_read_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:634: undefined reference to `inflateInit2_'
htslib/libhts.a(bgzf.o): In function `inflate_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:413: undefined reference to `inflateEnd'
htslib/libhts.a(bgzf.o): In function `bgzf_close':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:983: undefined reference to `deflateEnd'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:982: undefined reference to `inflateEnd'
htslib/libhts.a(hts.o): In function `decompress_peek':
/home/li/scrna-subsets-master/bin/htslib/hts.c:141: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/hts.c:144: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/hts.c:147: undefined reference to `inflateEnd'
/home/li/scrna-subsets-master/bin/htslib/hts.c:147: undefined reference to `inflateEnd'
htslib/libhts.a(cram_io.o): In function `zlib_mem_deflate':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:787: undefined reference to `deflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:801: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:808: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:813: undefined reference to `deflateEnd'
htslib/libhts.a(cram_io.o): In function `itf8_decode_crc':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:221: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:230: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:206: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:213: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:200: undefined reference to `crc32'
htslib/libhts.a(cram_io.o):/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:617: more undefined references to `crc32' follow
htslib/libhts.a(cram_io.o): In function `zlib_mem_inflate':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:723: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:736: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:756: undefined reference to `inflateEnd'
htslib/libhts.a(cram_io.o): In function `cram_read_block':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:951: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:953: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:985: undefined reference to `crc32'
htslib/libhts.a(cram_io.o): In function `cram_write_block':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:1054: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:1059: undefined reference to `crc32'
htslib/libhts.a(cram_io.o):/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:3123: more undefined references to `crc32' follow
htslib/libhts.a(zfio.o): In function `zfputs':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:80: undefined reference to `gzputs'
htslib/libhts.a(zfio.o): In function `zfpeek':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:97: undefined reference to `gzungetc'
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:95: undefined reference to `gzgetc'
htslib/libhts.a(zfio.o): In function `zfopen':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:165: undefined reference to `gzopen'
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:169: undefined reference to `gzopen'
htslib/libhts.a(zfio.o): In function `zfclose':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:180: undefined reference to `gzclose'
htslib/libhts.a(zfio.o): In function `zfgets':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:69: undefined reference to `gzgets'
htslib/libhts.a(zfio.o): In function `zfeof':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:105: undefined reference to `gzeof'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'barcode_tag_bam' failed
make: *** [barcode_tag_bam] Error 1
```

**Comment by kriemo** [comment]
it looks like you need to build the `htslib` library:

Try this:
```bash
cd /home/li/scrna-subsets-master/bin/htslib/
make
cd ..
make
```

**Comment by yueli8** [comment]
Hello, kriemo,

Thank you so much for your suggestion!
Thank you again!

Best,

Yue

```
li@Desktop-590-p0xxx:~/scrna-subsets-master/bin/htslib$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h
config.status: config.h is unchanged

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin/htslib$ make
gcc -g -O2 -I.  -c -o kfunc.o kfunc.c
gcc -g -O2 -I.  -c -o knetfile.o knetfile.c
gcc -g -O2 -I.  -c -o kstring.o kstring.c
gcc -g -O2 -I.  -c -o bgzf.o bgzf.c
gcc -g -O2 -I.  -c -o faidx.o faidx.c
gcc -g -O2 -I.  -c -o hfile.o hfile.c
gcc -g -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.3.2"' > version.h
gcc -g -O2 -I.  -c -o hts.o hts.c
gcc -g -O2 -I.  -c -o md5.o md5.c
gcc -g -O2 -I.  -c -o regidx.o regidx.c
gcc -g -O2 -I.  -c -o sam.o sam.c
gcc -g -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -O2 -I.  -c -o tbx.o tbx.c
gcc -g -O2 -I.  -c -o vcf.o vcf.c
gcc -g -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -O2 -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -O2 -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -O2 -I.  -c -o cram/files.o cram/files.c
gcc -g -O2 -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -O2 -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -O2 -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -O2 -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -O2 -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -O2 -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -O2 -I.  -c -o cram/thread_pool.o cram/thread_pool.c
gcc -g -O2 -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -O2 -I.  -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o md5.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o 
ranlib libhts.a
gcc -g -O2 -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -O2 -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -O2 -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -O2 -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -O2 -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -O2 -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -O2 -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -O2 -I.  -fpic -c -o hts.pico hts.c
gcc -g -O2 -I.  -fpic -c -o md5.pico md5.c
gcc -g -O2 -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -O2 -I.  -fpic -c -o sam.pico sam.c
gcc -g -O2 -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -O2 -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -O2 -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -O2 -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -O2 -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -O2 -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -O2 -I.  -fpic -c -o cram/files.pico cram/files.c
gcc -g -O2 -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -O2 -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -O2 -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -O2 -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -O2 -I.  -fpic -c -o cram/sam_header.pico cram/sam_header.c
gcc -g -O2 -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -g -O2 -I.  -fpic -c -o cram/thread_pool.pico cram/thread_pool.c
gcc -g -O2 -I.  -fpic -c -o cram/vlen.pico cram/vlen.c
gcc -g -O2 -I.  -fpic -c -o cram/zfio.pico cram/zfio.c
gcc -shared -Wl,-soname,libhts.so.1 -pthread   -o libhts.so kfunc.pico knetfile.pico kstring.pico bgzf.pico faidx.pico hfile.pico hfile_net.pico hts.pico md5.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico cram/thread_pool.pico cram/vlen.pico cram/zfio.pico -lz -lm  
ln -sf libhts.so libhts.so.1
gcc -g -O2 -I.  -c -o bgzip.o bgzip.c
gcc -pthread   -o bgzip bgzip.o libhts.a -lz  
gcc -g -O2 -I.  -c -o htsfile.o htsfile.c
gcc -pthread   -o htsfile htsfile.o libhts.a -lz  
gcc -g -O2 -I.  -c -o tabix.o tabix.c
gcc -pthread   -o tabix tabix.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc -pthread   -o test/fieldarith test/fieldarith.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/hfile.o test/hfile.c
gcc -pthread   -o test/hfile test/hfile.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/sam.o test/sam.c
gcc -pthread   -o test/sam test/sam.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc -pthread   -o test/test-regidx test/test-regidx.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/test_view.o test/test_view.c
gcc -pthread   -o test/test_view test/test_view.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc -pthread   -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz  
gcc -g -O2 -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc -pthread   -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz  

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin/htslib$ cd ..

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin$ make
g++ -ggdb -Wall -O2 -std=c++0x  -Ihtslib -o barcode_tag_bam barcode_tag_bam.cpp bamreader.cpp molecules.cpp -lz -lm -lpthread htslib/libhts.a
barcode_tag_bam.cpp: In function ‘int main(int, char**)’:
barcode_tag_bam.cpp:76:16: warning: ignoring return value of ‘int sam_hdr_write(samFile*, const bam_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
   sam_hdr_write(fp_out, header) ;
   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
barcode_tag_bam.cpp:115:15: warning: ignoring return value of ‘int sam_write1(samFile*, const bam_hdr_t*, const bam1_t*)’, declared with attribute warn_unused_result [-Wunused-result]
     sam_write1(fp_out, header, aln) ; //write alignment
     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
htslib/libhts.a(bgzf.o): In function `bgzf_write_init':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:209: undefined reference to `deflateInit2_'
htslib/libhts.a(bgzf.o): In function `inflate_gzip_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:451: undefined reference to `inflate'
htslib/libhts.a(bgzf.o): In function `bgzf_open':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:237: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_dopen':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:260: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_hopen':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:283: undefined reference to `compressBound'
htslib/libhts.a(bgzf.o): In function `bgzf_compress':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:311: undefined reference to `deflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:319: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:326: undefined reference to `deflateEnd'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:338: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:338: undefined reference to `crc32'
htslib/libhts.a(bgzf.o): In function `bgzf_gzip_compress':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:353: undefined reference to `deflate'
htslib/libhts.a(bgzf.o): In function `inflate_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:399: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:408: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:422: undefined reference to `inflateEnd'
htslib/libhts.a(bgzf.o): In function `bgzf_read_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:634: undefined reference to `inflateInit2_'
htslib/libhts.a(bgzf.o): In function `inflate_block':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:413: undefined reference to `inflateEnd'
htslib/libhts.a(bgzf.o): In function `bgzf_close':
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:983: undefined reference to `deflateEnd'
/home/li/scrna-subsets-master/bin/htslib/bgzf.c:982: undefined reference to `inflateEnd'
htslib/libhts.a(hts.o): In function `decompress_peek':
/home/li/scrna-subsets-master/bin/htslib/hts.c:141: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/hts.c:144: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/hts.c:147: undefined reference to `inflateEnd'
/home/li/scrna-subsets-master/bin/htslib/hts.c:147: undefined reference to `inflateEnd'
htslib/libhts.a(cram_io.o): In function `zlib_mem_deflate':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:787: undefined reference to `deflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:801: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:808: undefined reference to `deflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:813: undefined reference to `deflateEnd'
htslib/libhts.a(cram_io.o): In function `itf8_decode_crc':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:221: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:230: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:206: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:213: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:200: undefined reference to `crc32'
htslib/libhts.a(cram_io.o):/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:617: more undefined references to `crc32' follow
htslib/libhts.a(cram_io.o): In function `zlib_mem_inflate':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:723: undefined reference to `inflateInit2_'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:736: undefined reference to `inflate'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:756: undefined reference to `inflateEnd'
htslib/libhts.a(cram_io.o): In function `cram_read_block':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:951: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:953: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:985: undefined reference to `crc32'
htslib/libhts.a(cram_io.o): In function `cram_write_block':
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:1054: undefined reference to `crc32'
/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:1059: undefined reference to `crc32'
htslib/libhts.a(cram_io.o):/home/li/scrna-subsets-master/bin/htslib/cram/cram_io.c:3123: more undefined references to `crc32' follow
htslib/libhts.a(zfio.o): In function `zfputs':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:80: undefined reference to `gzputs'
htslib/libhts.a(zfio.o): In function `zfpeek':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:97: undefined reference to `gzungetc'
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:95: undefined reference to `gzgetc'
htslib/libhts.a(zfio.o): In function `zfopen':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:165: undefined reference to `gzopen'
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:169: undefined reference to `gzopen'
htslib/libhts.a(zfio.o): In function `zfclose':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:180: undefined reference to `gzclose'
htslib/libhts.a(zfio.o): In function `zfgets':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:69: undefined reference to `gzgets'
htslib/libhts.a(zfio.o): In function `zfeof':
/home/li/scrna-subsets-master/bin/htslib/cram/zfio.c:105: undefined reference to `gzeof'
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'barcode_tag_bam' failed
make: *** [barcode_tag_bam] Error 1

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin$ cd htslib/

li@Desktop-590-p0xxx:~/scrna-subsets-master/bin/htslib$ make install
mkdir -p -m 755 /usr/local/bin /usr/local/include /usr/local/include/htslib /usr/local/lib /usr/local/share/man/man1 /usr/local/share/man/man5 /usr/local/lib/pkgconfig
if test -n ""; then mkdir -p -m 755 ; fi
install -p -m 644 libhts.so /usr/local/lib/libhts.so.1.3.2
install: cannot remove '/usr/local/lib/libhts.so.1.3.2': Permission denied
Makefile:363: recipe for target 'install-so' failed
make: *** [install-so] Error 1

```

**Comment by kriemo** [comment]
What OS are you using?  This code was only tested on macOs and linux

**Comment by yueli8** [comment]
Hello, kriemo,

Thank you for your message!

I think I was wrong in  ` "make: *** [install-so] Error 1"`. I searched google and no idea.

I worked in `Linux: Ubuntu 18.04.3 LTS \n \l`.

Thank you again!

Best,


Yue

**Comment by kriemo** [comment]
I am not sure why there is a compilation error, I retested it on macOS and linux (rhel fedora) and it compiles without error. You may need to tweak the makefile to get it to compile on your system.

**Comment by yueli8** [comment]
Hello, kriemo,

Thank you so much for your explanation!

I will feedback to you if I have any progress.

Thank you again!

Best,

Yue

**Comment by kriemo** [comment]
Ok. Feel free to reopen if you have any progress.
